### ISSUE TITLE
VanillaCommandBlock: Bookshelf become Repeating Command Block

### ISSUE THREAD

**Issue by good777LUCKY** [PowerNukkit/PowerNukkit#311]
# 🐞 I found a bug

### 📸 Screenshots / Videos

Sorry i don't have video yet.

### ▶ Steps to Reproduce

1. Place a bookshelf
2. It becomes repeating command block.

### ✔ Expected Behavior

Bookshelf should be placed.

### ❌ Actual Behavior

Repeating Command Block placed.

### 📋 Debug information

* PowerNukkit version: PN-115 latest (a80287f)
* Debug link: 
* Timings link (if relevant):

**Comment by MrRazamataz** [comment]
@good777LUCKY 
Do you have a plugin installed that is meant to enable command blocks? I had this on my server and had the same bookshelf issues and when I removed the command block plugin, it solved the problem. I think it was that the plugin uses the old blocks ids buy im not certain on that.

**Comment by good777LUCKY** [comment]
Oh I think it is because of command block plugin. I will remove it.

**Comment by joserobjr** [comment]
@good777LUCKY is that plugin public? I'm curious about what was making it place the wrong block

**Comment by tuilakhanh** [comment]
@joserobjr https://github.com/wode490390/VanillaCommands

His github has a lot of great plugins, so you should check it out

**Comment by MrRazamataz** [comment]
@joserobjr Yes it is public. I will try to find the link.

**Comment by MrRazamataz** [comment]
Oh. tulia already sent a github link. ok

**Comment by joserobjr** [comment]
Reopening so I can take a look to see if I can do something to recover the compatibility

**Comment by good777LUCKY** [comment]
> @good777LUCKY is that plugin public? I'm curious about what was making it place the wrong block

https://github.com/wode490390/VanillaCommandBlock

**Comment by joserobjr** [comment]
Hmm I know the problem now, it's the freaking `fullList`
https://github.com/wode490390/VanillaCommandBlock/blob/335021f229c7a68da940895e33338e4020cbf04a/src/main/java/cn/wode490390/nukkit/cmdblock/CommandBlockPlugin.java#L58

We had to change it to hold 6 bits instead of 4 in the past. Now we introduced a hyper-id system that works apart from the fullList but only the wall block is using it.

In the next major release, I'm going to change it back to 4 and all blocks which need 5+ bits will start using the hyper-id system. This should recover the compatibility with plugins that interact with this list directly.
