### ISSUE TITLE
Shulker Boxes crash client whilst standing on top and opening them.

### ISSUE THREAD

**Issue by MrRazamataz** [PowerNukkit/PowerNukkit#339]
https://www.youtube.com/watch?v=PdssncAdCw4&feature=youtu.be 
1.3.1.0-SNAPSHOT 3a4f1ba

**Comment by MrRazamataz** [comment]
I run /about in the video.

**Comment by MrRazamataz** [comment]
Only works in survival.

**Comment by joserobjr** [comment]
I think this can be caused by a plugin, latency or was already resolved somehow. I did the same but I didn't crash:
https://youtu.be/vmzOCfcMvto

The test was at d94aeee2e22b93bbae785d1704a9a954f379d715

**Comment by joserobjr** [comment]
I don't think that changes between our version could fix this issue.
https://github.com/GameModsBR/PowerNukkit/compare/3a4f1ba...d94aeee

I also tested using the same commit as you but the issue didn't happen on a clean server. I'm going to test on a remote server.

**Comment by joserobjr** [comment]
I tested online with ping around `105` and my client didn't crash. Can you reproduce it without plugins? If it's a plugin issue we will need to investigate which plugin is causing this crash and find possible solutions.

**Comment by MrRazamataz** [comment]
Sometimes it can crash the client. #339

**Comment by MrRazamataz** [comment]
Ok I will try it again on my server as it may have been fixed. If it hasn't been fixed I will try on a clean server.

**Comment by joserobjr** [comment]
Hi. Is the issue still happening?

**Comment by joserobjr** [comment]
A hotfix was added at https://github.com/PowerNukkit/PowerNukkit/commit/f297558e5f1ac8c96c9690447b20dbc143e33891 , it prevents client crashes that were happening sometimes when the player closes inventories, I think it should fix the issue if it still happens.

Closing it as stale because a possible fix has been committed and the issue was awaiting response for 14 days. If it still happens you can reopen.
