### ISSUE TITLE
Latest bleed version turns everything that has been worldedited into UPDATE blocks. 

### ISSUE THREAD

**Issue by MrRazamataz** [PowerNukkit/PowerNukkit#357]
This turns all things that have had something to do with FAWE into update blocks into UPDATE blocks.(https://github.com/GameModsBR/PowerNukkit/actions/runs/165340406). It can be fixed by downgrading back to (https://github.com/GameModsBR/PowerNukkit/actions/runs/164051480).
![image](https://user-images.githubusercontent.com/56600481/87222892-cd37e500-c36f-11ea-88fd-2b9046da836d.png)

**Comment by joserobjr** [comment]
Can you send a sample region file? I think it is related to a bug in FAWE which makes it save air blocks with metadata. The previous version had a compatibility gate for that issue. I've rewritten that class recently and I might have forgotten to test that gate.

That update blocks are only visual, that's the way the server says that it doesn't know how to display that block.

I'm going to fix that compatibility issue but if you send a MCA file will help me to see if there are more compatibility issues (I think I'm seeing some odd update block slabs there which I didn't know that was possible lol).

I also removed the urgent word from the title since this is from the bleeding branch which is a beta testing branch.

**Comment by joserobjr** [comment]
If confirmed, it's a regression from the issue #210

**Comment by joserobjr** [comment]
This build and higher fixes the issue, if you still get any update block (visually or logged as error), than I'm going to need a region sample (you can send it privately at [discord](https://powernukkit.org/discord) if you prefer)

If everything is fine than it's not needed,

**Comment by MrRazamataz** [comment]
Ok. Yeah I guess it's not Urgent as it's in bleeding branch. 
How would I send you a region file of an area of my choosing.

**Comment by joserobjr** [comment]
Put the block coordinate in this calculator (inside the `Block Information`)
https://minecraft.tools/en/coordinate-calculator.php

The `Region Informations` have a `file` field, that is the region file that contains the block, it's located inside the `region` folder of your world, like:
`worlds/<name>/region/r.<number>.<number>.mca`
