### ISSUE TITLE
Provide Maven packages of PowerNukkit

### ISSUE THREAD

**Issue by AntonPPDS** [PowerNukkit/PowerNukkit#401]
Since there is more plugin events, offhand slot etc., it would be a nice to provide a PowerNukkit package so plugins can use it as a dependency. I saw that there is one such on GitHub, but it is outdated.

**Comment by Htepple** [comment]
If you are an experienced maven user you would never ask for such a thing. You can always add repositories yourself.

**Comment by joserobjr** [comment]
The issue is that I need to deploy it using FTP, I won't be hosting nexus oss or other memory hungry software to share static files lol

I know how to do it using gradle but I have no idea on how to do it with maven. This is how I do it with gradle in an other project:
https://github.com/AsyncMC/RakNet-Protocol/blob/69bff154ae71611b6076ba026255ecf284a90f85/build.gradle.kts#L159-L187

I also need it to be property-based because I plan on deploying the final releases to jcenter but send the snapshots to our own web servers

**Comment by joserobjr** [comment]
PowerNukkit releases and snapshots are now accessible by maven central (releases), jcenter (releases) and Sonatype OSS Snapshots (snapshots)

https://discuss.powernukkit.org/t/how-to-add-maven-dependency-to-powernukkit/50?u=joserobjr
