### ISSUE TITLE
AntiXray compatibility

### ISSUE THREAD

**Issue by tuilakhanh** [PowerNukkit/PowerNukkit#424]
# 🔌 Plugin compatibility issue
AntiXray plugin
https://github.com/wode490390/AntiXray

### 📸 Screenshots / Videos

Not yet

### ▶ Steps to Reproduce

1. Run plugin
2. It have an error

### 📋 Debug information

* PowerNukkit version: ✍ 
* Debug link: ✍
* Timings link (if relevant): ✍ 

### 💢 Crash Dump, Stack Trace and Other Files

https://debugpaste.powernukkit.org/pastes/ewomilenak

**Comment by joserobjr** [comment]
I got the commit hashes from your edit history.

171e0b2
cac23287781bf9755beebfd40b7b982e705dbe8c

To make it become a link you just need to paste it directly.

**Comment by joserobjr** [comment]
Unfortunately, the plugin is doing reflections to modify internal server structures. It's not supported can not be fixed by PowerNukkit side.

Also, doing a quick look at the code, it could break the high-id/data support, have other compatibility issues and cause a big performance impact.

If you or anyone really need this plugin, please, open a new thread at https://discuss.powernukkit.org/c/plugins/6 asking for a port.
