### ISSUE TITLE
Debugpaste does not work

### ISSUE THREAD

**Issue by Plugner** [PowerNukkit/PowerNukkit#535]
# 🐞 I found a bug

### 📸 Screenshots / Videos

![image](https://user-images.githubusercontent.com/48152341/91648390-6d8bbb00-ea3d-11ea-84df-94c237f694a0.png)

### ▶ Steps to Reproduce

1. Write: /debugpaste in console/chat 

### ✔ Expected Behavior

Give the debug in hastebin

### ❌ Actual Behavior

Throws a error.

### 📋 Debug information

* PowerNukkit version: ✍ 1.3.1.4-PN
* Debug link: ✍ Does not working :D
* Timings link (if relevant): ✍ 

### 💢 Crash Dump, Stack Trace and Other Files

![image](https://user-images.githubusercontent.com/48152341/91648405-8e541080-ea3d-11ea-9dc7-8caff2af70da.png)

**Comment by joserobjr** [comment]
It is usually a temporary issue, it happens when hastebin.com is overloaded. It is also possible that it has blacklisted your IP.

But I'm going to keep this open as an enhancement request because we are transitioning away from it, to preserve the pastes for a longer period and to prune unneeded details like player IPs and server ports, etc.

**Comment by LoboMetalurgico** [comment]
Closing as fixed.
