### ISSUE TITLE
FastAsyncWorldEdit has problems loading

### ISSUE THREAD

**Issue by bobbyl140** [PowerNukkit/PowerNukkit#561]
# 🔌 Plugin compatibility issue

### 📸 Screenshots / Videos

![FAWE Error](https://user-images.githubusercontent.com/61990607/92127512-6236e780-edcf-11ea-8cd4-12ca9fcb60d4.png)

### ▶ Steps to Reproduce

1. Make a server with any recent version of 1.4.0.0, and install FAWE.
2. Boot up the server.
3. See the error 

### ✔ Expected Behavior
FAWE starts normally, and functions work

### ❌ Actual Behavior
It doesn't load properly and in game commands such as //wand do nothing.

### 📋 Debug information

* PowerNukkit version: 1.4.0.0-PN-SNAPSHOT (git-c885016)
* Debug link: https://debugpaste.powernukkit.org/pastes/zituyuxida
* Timings link (if relevant): ✍

**Comment by joserobjr** [comment]
Hello, thank you for opening a report.

I believe that's a compatibility issue between FastAyncWorldEdit and Java 9+ and not a compatibility issue with PowerNukkit itself.

Please, check if the issue still happens when you run the server using Java 8.

Currently, we don't recommend running the server with Java versions higher than 8 because they added restrictions to reflections that can cause errors like that.

**Comment by bobbyl140** [comment]
Thank you, I upgraded to Java 11 a while ago. Downgrading fixed it, thanks again.

**Comment by joserobjr** [comment]
Awesome! Thank you for letting us know that it worked 👍
