### ISSUE TITLE
Creative inventory is not sorted

### ISSUE THREAD

**Issue by LucGamesYT** [PowerNukkit/PowerNukkit#857]
# 🐞 I found a bug

### ✔ Expected Behavior
Sorted creative inventar

### ❌ Actual Behavior
The items are not always in the right place

![image](https://user-images.githubusercontent.com/19286296/102924542-14cfaa80-4492-11eb-9c01-2dedd6004180.png)
![image](https://user-images.githubusercontent.com/19286296/102924559-1dc07c00-4492-11eb-8a1b-c979aff4c438.png)

**Comment by LucGamesYT** [comment]
Version: https://hastebin.com/ufiqalakul

**Comment by joserobjr** [comment]
## ✔ Expected Behavior
![image](https://user-images.githubusercontent.com/3679022/102928635-d75e2380-4477-11eb-8789-5e7fce3ebd9d.png)
![image](https://user-images.githubusercontent.com/3679022/102928642-daf1aa80-4477-11eb-915a-bbefee0f28bd.png)
![image](https://user-images.githubusercontent.com/3679022/102928650-df1dc800-4477-11eb-8a6f-2684c17a91f6.png)
![image](https://user-images.githubusercontent.com/3679022/102928661-e47b1280-4477-11eb-913f-9b7e771f326c.png)

**Comment by wolf-yuan-6115** [comment]
Yea me too
